# Framework Execution Configuration
# Mobile Configuration (Android)
mobile.platformName=Android
mobile.automationName=UiAutomator2
mobile.deviceName=Android Device
# We will place the APK in the apps directory at the root of the project
mobile.app=${user.dir}/apps/Android-MyDemoAppRN.1.3.0.build-244.apk
mobile.appPackage=com.saucelabs.mydemoapp.rn
mobile.appActivity=.MainActivity
mobile.noReset=false
mobile.fullReset=false

# Appium Server Configuration
appium.server.url=http://127.0.0.1:4723
